# Use postgres/example user/password credentials
version: '3.9'

services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports: 
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: 111
      POSTGRES_USER: ps
      POSTGRES_DB: app
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: